services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./backend/storage/app/public:/var/www/storage/app/public:ro
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/storage/app/public:/var/www/html/storage/app/public
    environment:
      APP_NAME: Cinema
      APP_ENV: local
      APP_KEY: base64:+cnSaORWtM2fuS+si1GhelM2xk4htr8E0El8bSDOGYI=
      APP_DEBUG: "true"
      APP_URL: http://localhost
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: cinema
      DB_USERNAME: cinema
      DB_PASSWORD: cinema
      CACHE_STORE: array
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: array
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: cinema
      POSTGRES_USER: cinema
      POSTGRES_PASSWORD: cinema
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cinema -d cinema"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
